DROP PROCEDURE IF EXISTS dropNameColumn;

DELIMITER //
CREATE PROCEDURE dropNameColumn()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_VOLUNTEER' AND column_name='name') THEN

ALTER TABLE BOOKING_APP_VOLUNTEER DROP COLUMN `name`;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_VOLUNTEER__TRASH' AND column_name='name') THEN

ALTER TABLE BOOKING_APP_VOLUNTEER__TRASH DROP COLUMN `name`;

END IF;

END//

DELIMITER ;

CALL dropNameColumn();

DROP PROCEDURE IF EXISTS dropNameColumn;