DROP PROCEDURE IF EXISTS removeNotNullConstraint;

DELIMITER //
CREATE PROCEDURE removeNotNullConstraint()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_SCREENING') THEN

ALTER TABLE BOOKING_APP_SCREENING MODIFY COLUMN startTime varchar(255) CHARACTER SET latin1 COLLATE latin1_bin;
ALTER TABLE BOOKING_APP_SCREENING MODIFY COLUMN endTime varchar(255) CHARACTER SET latin1 COLLATE latin1_bin;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_SCREENING__TRASH') THEN

ALTER TABLE BOOKING_APP_SCREENING__TRASH MODIFY COLUMN startTime varchar(255) CHARACTER SET latin1 COLLATE latin1_bin;
ALTER TABLE BOOKING_APP_SCREENING__TRASH MODIFY COLUMN endTime varchar(255) CHARACTER SET latin1 COLLATE latin1_bin;

END IF;

END//

DELIMITER ;

CALL removeNotNullConstraint();

DROP PROCEDURE IF EXISTS removeNotNullConstraint;
