DROP PROCEDURE IF EXISTS removeNotNullConstraintFromClinicIdOidColumn;

DELIMITER //
CREATE PROCEDURE removeNotNullConstraintFromClinicIdOidColumn()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_UNSCHEDULEDVISIT') THEN

ALTER TABLE BOOKING_APP_UNSCHEDULEDVISIT MODIFY COLUMN clinic_id_OID bigint(20) DEFAULT NULL;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_UNSCHEDULEDVISIT__TRASH' AND column_name='clinic_id_OID') THEN

ALTER TABLE BOOKING_APP_UNSCHEDULEDVISIT__TRASH MODIFY COLUMN clinic_id_OID bigint(20) DEFAULT NULL;
END IF;

END//

DELIMITER ;

CALL removeNotNullConstraintFromClinicIdOidColumn();

DROP PROCEDURE IF EXISTS removeNotNullConstraintFromClinicIdOidColumn;
