DROP PROCEDURE IF EXISTS addScreeningStatusColumn;

DELIMITER //
CREATE PROCEDURE addScreeningStatusColumn()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_SCREENING') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_SCREENING' AND column_name='status') THEN

ALTER TABLE BOOKING_APP_SCREENING ADD `status` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;

END IF;

UPDATE BOOKING_APP_SCREENING SET status = 'ACTIVE' WHERE status IS NULL OR status = '';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_SCREENING__TRASH') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_SCREENING__TRASH' AND column_name='status') THEN

ALTER TABLE BOOKING_APP_SCREENING__TRASH ADD `status` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;

END IF;

UPDATE BOOKING_APP_SCREENING__TRASH SET status = 'ACTIVE' WHERE status IS NULL OR status = '';

END IF;

END//

DELIMITER ;

CALL addScreeningStatusColumn();

DROP PROCEDURE IF EXISTS addScreeningStatusColumn;