DROP PROCEDURE IF EXISTS dropUniqueConstraint;

DELIMITER //
CREATE PROCEDURE dropUniqueConstraint()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT' AND index_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT_U1') THEN

ALTER TABLE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT DROP INDEX EBODAC_MODULE_IVRANDSMSSTATISTICREPORT_U1;

END IF;

END//

DELIMITER ;

CALL dropUniqueConstraint();

DROP PROCEDURE IF EXISTS dropUniqueConstraint;
