DROP PROCEDURE IF EXISTS updateVisitType;

DELIMITER //
CREATE PROCEDURE updateVisitType()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_VISIT') THEN

UPDATE EBODAC_MODULE_VISIT SET type = 'PRIME_VACCINATION_FIRST_FOLLOW_UP_VISIT' WHERE type = 'PRIME_VACCINATION_FOLLOW_UP_VISIT';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_VISIT__HISTORY') THEN

UPDATE EBODAC_MODULE_VISIT__HISTORY SET type = 'PRIME_VACCINATION_FIRST_FOLLOW_UP_VISIT' WHERE type = 'PRIME_VACCINATION_FOLLOW_UP_VISIT';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_VISIT__TRASH') THEN

UPDATE EBODAC_MODULE_VISIT__TRASH SET type = 'PRIME_VACCINATION_FIRST_FOLLOW_UP_VISIT' WHERE type = 'PRIME_VACCINATION_FOLLOW_UP_VISIT';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT') THEN

UPDATE EBODAC_MODULE_ENROLLMENT SET campaignName = 'Prime Vaccination First Follow-up visit' WHERE campaignName = 'Prime Vaccination Follow-up visit';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT__TRASH') THEN

UPDATE EBODAC_MODULE_ENROLLMENT__TRASH SET campaignName = 'Prime Vaccination First Follow-up visit' WHERE campaignName = 'Prime Vaccination Follow-up visit';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_VISITSCHEDULEOFFSET') THEN

UPDATE BOOKING_APP_VISITSCHEDULEOFFSET SET visitType = 'PRIME_VACCINATION_FIRST_FOLLOW_UP_VISIT' WHERE visitType = 'PRIME_VACCINATION_FOLLOW_UP_VISIT';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_VISITSCHEDULEOFFSET__TRASH') THEN

UPDATE BOOKING_APP_VISITSCHEDULEOFFSET__TRASH SET visitType = 'PRIME_VACCINATION_FIRST_FOLLOW_UP_VISIT' WHERE visitType = 'PRIME_VACCINATION_FOLLOW_UP_VISIT';

END IF;

END//

DELIMITER ;

CALL updateVisitType();

DROP PROCEDURE IF EXISTS updateVisitType;

DROP PROCEDURE IF EXISTS dropMaxPrimeFollowUpVisits;

DELIMITER //
CREATE PROCEDURE dropMaxPrimeFollowUpVisits()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_CLINIC' AND column_name='maxPrimeFollowUpVisits') THEN

ALTER TABLE BOOKING_APP_CLINIC DROP COLUMN `maxPrimeFollowUpVisits`;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='BOOKING_APP_CLINIC__TRASH' AND column_name='maxPrimeFollowUpVisits') THEN

ALTER TABLE BOOKING_APP_CLINIC__TRASH DROP COLUMN `maxPrimeFollowUpVisits`;

END IF;

END//

DELIMITER ;

CALL dropMaxPrimeFollowUpVisits();

DROP PROCEDURE IF EXISTS dropMaxPrimeFollowUpVisits;