DROP PROCEDURE IF EXISTS removeNotNullConstraint;

DELIMITER //
CREATE PROCEDURE removeNotNullConstraint()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_SUBJECT') THEN

ALTER TABLE EBODAC_MODULE_SUBJECT MODIFY COLUMN siteId varchar(255) CHARACTER SET latin1 COLLATE latin1_bin;

UPDATE EBODAC_MODULE_SUBJECT SET siteName = 'Kambia I' WHERE siteName IS NULL;

ALTER TABLE EBODAC_MODULE_SUBJECT MODIFY COLUMN siteName varchar(255) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_SUBJECT__HISTORY') THEN

ALTER TABLE EBODAC_MODULE_SUBJECT__HISTORY MODIFY COLUMN siteId varchar(255) CHARACTER SET latin1 COLLATE latin1_bin;

UPDATE EBODAC_MODULE_SUBJECT__HISTORY SET siteName = 'Kambia I' WHERE siteName IS NULL;

ALTER TABLE EBODAC_MODULE_SUBJECT__HISTORY MODIFY COLUMN siteName varchar(255) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_SUBJECT__TRASH') THEN

ALTER TABLE EBODAC_MODULE_SUBJECT__TRASH MODIFY COLUMN siteId varchar(255) CHARACTER SET latin1 COLLATE latin1_bin;

UPDATE EBODAC_MODULE_SUBJECT__TRASH SET siteName = 'Kambia I' WHERE siteName IS NULL;

ALTER TABLE EBODAC_MODULE_SUBJECT__TRASH MODIFY COLUMN siteName varchar(255) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL;

END IF;

END//

DELIMITER ;

CALL removeNotNullConstraint();

DROP PROCEDURE IF EXISTS removeNotNullConstraint;
