DROP PROCEDURE IF EXISTS addSmsStatusColumn;

DELIMITER //
CREATE PROCEDURE addSmsStatusColumn()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT' AND column_name='smsStatus') THEN

ALTER TABLE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT ADD `smsStatus` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;

END IF;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH' AND column_name='smsStatus') THEN

ALTER TABLE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH ADD `smsStatus` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;

END IF;

END IF;

END//

DELIMITER ;

CALL addSmsStatusColumn();

DROP PROCEDURE IF EXISTS addSmsStatusColumn;

DROP PROCEDURE IF EXISTS updateSmsStatus;

DELIMITER //
CREATE PROCEDURE updateSmsStatus()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT' AND column_name='sms') THEN

UPDATE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT SET smsStatus = 'YES' WHERE sms = 1;
UPDATE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT SET smsStatus = 'NO' WHERE sms = 0;
UPDATE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT SET smsStatus = 'FAIL' WHERE smsFailed = 1;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH' AND column_name='sms') THEN

UPDATE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH SET smsStatus = 'YES' WHERE sms = 1;
UPDATE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH SET smsStatus = 'NO' WHERE sms = 0;
UPDATE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH SET smsStatus = 'FAIL' WHERE smsFailed = 1;

END IF;

END//

DELIMITER ;

CALL updateSmsStatus();

DROP PROCEDURE IF EXISTS updateSmsStatus;

DROP PROCEDURE IF EXISTS dropSmsAndSmsFailedColumns;

DELIMITER //
CREATE PROCEDURE dropSmsAndSmsFailedColumns()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT' AND column_name='sms') THEN

ALTER TABLE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT DROP COLUMN `sms`;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH' AND column_name='sms') THEN

ALTER TABLE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH DROP COLUMN `sms`;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT' AND column_name='smsFailed') THEN

ALTER TABLE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT DROP COLUMN `smsFailed`;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH' AND column_name='smsFailed') THEN

ALTER TABLE EBODAC_MODULE_IVRANDSMSSTATISTICREPORT__TRASH DROP COLUMN `smsFailed`;

END IF;

END//

DELIMITER ;

CALL dropSmsAndSmsFailedColumns();

DROP PROCEDURE IF EXISTS dropSmsAndSmsFailedColumns;