DROP PROCEDURE IF EXISTS addEmailReportStatusColumn;

DELIMITER //
CREATE PROCEDURE addEmailReportStatusColumn()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_EMAILREPORT') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_EMAILREPORT' AND column_name='status') THEN

ALTER TABLE EBODAC_MODULE_EMAILREPORT ADD `status` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;

END IF;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_EMAILREPORT__TRASH') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_EMAILREPORT__TRASH' AND column_name='status') THEN

ALTER TABLE EBODAC_MODULE_EMAILREPORT__TRASH ADD `status` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL;

END IF;

END IF;

END//

DELIMITER ;

CALL addEmailReportStatusColumn();

DROP PROCEDURE IF EXISTS addEmailReportStatusColumn;

DROP PROCEDURE IF EXISTS updateEmailReportStatusColumn;

DELIMITER //
CREATE PROCEDURE updateEmailReportStatusColumn()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_EMAILREPORT' AND column_name='status') THEN

UPDATE EBODAC_MODULE_EMAILREPORT SET status = 'ENABLED' WHERE status IS NULL OR status = '';

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_EMAILREPORT__TRASH' AND column_name='status') THEN

UPDATE EBODAC_MODULE_EMAILREPORT__TRASH SET status = 'ENABLED' WHERE status IS NULL OR status = '';

END IF;

END//

DELIMITER ;

CALL updateEmailReportStatusColumn();

DROP PROCEDURE IF EXISTS updateEmailReportStatusColumn;
