DROP PROCEDURE IF EXISTS addStageIdColumn;

DELIMITER //
CREATE PROCEDURE addStageIdColumn()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT' AND column_name='stageId') THEN

ALTER TABLE EBODAC_MODULE_ENROLLMENT ADD `stageId` bigint(20) DEFAULT NULL;

END IF;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT__TRASH') THEN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT__TRASH' AND column_name='stageId') THEN

ALTER TABLE EBODAC_MODULE_ENROLLMENT__TRASH ADD `stageId` bigint(20) DEFAULT NULL;

END IF;

END IF;

END//

DELIMITER ;

CALL addStageIdColumn();

DROP PROCEDURE IF EXISTS addStageIdColumn;


DROP PROCEDURE IF EXISTS updateStageId;

DELIMITER //
CREATE PROCEDURE updateStageId()
BEGIN

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT' AND column_name='stageId') THEN

UPDATE EBODAC_MODULE_ENROLLMENT SET stageId = (CASE LOCATE(' - stage ', campaignName) WHEN 0 THEN 1 ELSE SUBSTRING_INDEX(campaignName, ' - stage ', -1) END) WHERE stageId IS NULL;

END IF;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema=DATABASE() AND table_name='EBODAC_MODULE_ENROLLMENT__TRASH' AND column_name='stageId') THEN

UPDATE EBODAC_MODULE_ENROLLMENT__TRASH SET stageId = (CASE LOCATE(' - stage ', campaignName) WHEN 0 THEN 1 ELSE SUBSTRING_INDEX(campaignName, ' - stage ', -1) END) WHERE stageId IS NULL;

END IF;

END//

DELIMITER ;

CALL updateStageId();

DROP PROCEDURE IF EXISTS updateStageId;


DROP PROCEDURE IF EXISTS removeStageIdAndBoostVacDayFromCampaignName;

DELIMITER //
CREATE PROCEDURE removeStageIdAndBoostVacDayFromCampaignName()
BEGIN

UPDATE EBODAC_MODULE_ENROLLMENT SET campaignName = SUBSTRING_INDEX(campaignName, ' - stage ', 1);

UPDATE EBODAC_MODULE_ENROLLMENT__TRASH SET campaignName = SUBSTRING_INDEX(campaignName, ' - stage ', 1);


UPDATE EBODAC_MODULE_ENROLLMENT SET campaignName = "Boost Vaccination Day" WHERE campaignName LIKE "Boost Vaccination Day%";

UPDATE EBODAC_MODULE_ENROLLMENT__TRASH SET campaignName = "Boost Vaccination Day" WHERE campaignName LIKE "Boost Vaccination Day%";

END//

DELIMITER ;

CALL removeStageIdAndBoostVacDayFromCampaignName();

DROP PROCEDURE IF EXISTS removeStageIdAndBoostVacDayFromCampaignName;